version: '3'

services:
  db:
    image: postgres:latest
    env_file:
      - environments/db.env
    volumes:
      - db_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d django_db" ]
      interval: 2s
      timeout: 1s
      retries: 3

  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    env_file:
      - environments/web.env
    volumes:
      - ./web:/code
    ports:
      - "8000:8000"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000" ]
      interval: 5s
      timeout: 3s
      retries: 3
    depends_on:
      db:
        condition: service_healthy

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./web:/code
    healthcheck:
      test: [ "CMD", "nginx", "-t" ]
      interval: 1s
      timeout: 2s
      retries: 3
    depends_on:
      db:
        condition: service_healthy
      web:
        condition: service_healthy

volumes:
  db_volume: