# Generated by Django 5.1.2 on 2024-10-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_referred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referral_code_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
